name: Build and Release macOS Launcher

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build macOS Application and Force Publish
        # 🚀 명령어 뒤에 설정을 직접 때려 박아 깃허브 맥 컴퓨터가 다른 생각을 못 하게 만듭니다.
        run: npx electron-builder --mac -c.publish.provider=github -c.publish.releaseType=draft --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}